<?php

namespace ContainerVPDOJfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DNWStjfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dNWStjf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dNWStjf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'listeRepository' => ['privates', 'App\\Repository\\ListeRepository', 'getListeRepositoryService', true],
        ], [
            'listeRepository' => 'App\\Repository\\ListeRepository',
        ]);
    }
}
