<?php

namespace ContainerVPDOJfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_63psbP1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.63psbP1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.63psbP1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'liste' => ['privates', '.errored..service_locator.63psbP1.App\\Entity\\Liste', NULL, 'Cannot autowire service ".service_locator.63psbP1": it references class "App\\Entity\\Liste" but no such service exists.'],
            'listeRepository' => ['privates', 'App\\Repository\\ListeRepository', 'getListeRepositoryService', true],
        ], [
            'liste' => 'App\\Entity\\Liste',
            'listeRepository' => 'App\\Repository\\ListeRepository',
        ]);
    }
}
