<?php

namespace ContainerVPDOJfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QaiGT.j.App\Entity\Dishes' shared service.
     *
     * @return \App\Entity\Dishes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QaiGT.j": it references class "App\\Entity\\Dishes" but no such service exists.');
    }
}
