<?php

namespace ContainerHfisquD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R6n4w_5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r6n4w.5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r6n4w.5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dr' => ['privates', 'App\\Repository\\DishesRepository', 'getDishesRepositoryService', true],
        ], [
            'dr' => 'App\\Repository\\DishesRepository',
        ]);
    }
}
