<?php

namespace ContainerHfisquD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EBp3G8CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eBp3G8C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eBp3G8C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dish' => ['privates', '.errored..service_locator.eBp3G8C.App\\Entity\\Dishes', NULL, 'Cannot autowire service ".service_locator.eBp3G8C": it references class "App\\Entity\\Dishes" but no such service exists.'],
        ], [
            'dish' => 'App\\Entity\\Dishes',
        ]);
    }
}
