<?php

namespace ContainerHfisquD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListe2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hKLna5N.App\Entity\Liste' shared service.
     *
     * @return \App\Entity\Liste
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hKLna5N": it references class "App\\Entity\\Liste" but no such service exists.');
    }
}
