<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVPDOJfD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVPDOJfD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVPDOJfD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVPDOJfD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVPDOJfD\App_KernelDevDebugContainer([
    'container.build_hash' => 'VPDOJfD',
    'container.build_id' => '02980229',
    'container.build_time' => 1659693990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVPDOJfD');
